---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  get-version:
    uses: GrabAByte/github-devops-workflows/.github/workflows/getVersion.yml@0.13.3
    with:
      metadataFile: 'metadata.json'
      metadataPath: .
  lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformLint.yml@0.13.3
    with:
      terraformPath: .
  validate:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformValidate.yml@0.13.3
    secrets:
      account: ${{ secrets.AWS_ACCOUNT }}
      role: ${{ secrets.AWS_ROLE }}
    with:
      region: eu-west-2
      terraformPath: .
    needs: [lint]
  scan:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformScan.yml@0.13.3
    with:
      terraformPath: .
    needs: [lint,validate]
  plan:
    strategy:
      matrix:
        workspaces: [development, pre-production, production]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformPlan.yml@0.13.3
    secrets:
      account: ${{ secrets.AWS_ACCOUNT }}
      role: ${{ secrets.AWS_ROLE }}
    with:
      region: eu-west-2
      terraformPath: .
      workspace: ${{ matrix.workspaces }}
    needs: [lint,validate,scan]

  ## temporarily disable functionality
  #apply:
  #  if: github.ref == 'refs/heads/main'
  #  strategy:
  #    matrix:
  #      workspaces: [development]
  #  uses: GrabAByte/github-devops-workflows/.github/workflows/terraformApply.yml@0.13.3
  #  secrets:
  #    account: ${{ secrets.AWS_ACCOUNT }}
  #    role: ${{ secrets.AWS_ROLE }}
  #  with:
  #    region: eu-west-2
  #    terraformPath: .
  #    workspace: ${{ matrix.workspaces }}
  #  needs: [lint,validate,scan,plan]
  #destroy:
  #  if: github.ref == 'refs/heads/main'
  #  strategy:
  #    matrix:
  #      workspaces: [development]
  #  uses: GrabAByte/github-devops-workflows/.github/workflows/terraformDestroy.yml@0.13.3
  #  secrets:
  #    account: ${{ secrets.AWS_ACCOUNT }}
  #    role: ${{ secrets.AWS_ROLE }}
  #  with:
  #    region: eu-west-2
  #    terraformPath: .
  #    workspace: ${{ matrix.workspaces }}
  #  needs: [lint,validate,scan,plan,apply]
  ##

  update-version:
    #if: github.ref == 'refs/heads/main'
    uses: GrabAByte/github-devops-workflows/.github/workflows/semanticRelease.yml@feat/semantic-release
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: [lint,validate,scan,plan]
