---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  get-version:
    uses: GrabAByte/github-devops-workflows/.github/workflows/getVersion.yml@0.12.0
    with:
      metadataFile: 'metadata.json'
      metadataPath: .
  lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformLint.yml@0.12.0
    with:
      terraformPath: .
  validate:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformValidate.yml@0.12.0
    with:
      terraformPath: .
    needs: [lint]
  scan:
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformScan.yml@0.12.0
    with:
      terraformPath: .
    needs: [lint,validate]
  plan:
    strategy:
      matrix:
        workspaces: [development, pre-production]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformPlan.yml@feat/manual-trigger-tf-apply
    secrets:
      account: ${{ secrets.AWS_ACCOUNT }}
      role: ${{ secrets.AWS_ROLE }}
    with:
      region: eu-west-2
      terraformPath: .
      workspace: ${{ matrix.workspaces }}
    needs: [lint,validate,scan]
  apply:
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        workspaces: [development]
    uses: GrabAByte/github-devops-workflows/.github/workflows/terraformApply.yml@feat/manual-trigger-tf-apply
    secrets:
      account: ${{ secrets.AWS_ACCOUNT }}
      role: ${{ secrets.AWS_ROLE }}
    with:
      region: eu-west-2
      terraformPath: .
      workspace: ${{ matrix.workspaces }}
    needs: [lint,validate,scan,plan]
  update-version:
    if: github.ref == 'refs/heads/main'
    uses: GrabAByte/github-devops-workflows/.github/workflows/updateVersion.yml@feat/manual-trigger-tf-apply
    with:
      gitUsername: 'grababyte'
      gitEmail: 'grababyte@github.com'
      metadataFile: 'metadata.json'
      metadataPath: .
    needs: [lint,validate,scan,plan,apply]
